version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/tasklist_manager
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1